//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Management_App_with_Subtasks_and_Deadlines.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTask
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Status { get; set; }
        public int Position { get; set; }
        public string Name { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
